### ISSUE TITLE
issue when synchronizing a set of files between computers ... does not detect end of stream

### ISSUE THREAD

**Issue by kif** [kif/imagizer#3]
INFO:imagizer.dialogs:building file list ... done

^CTraceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/imagizer/interface.py", line 217, in _action_handler
    callback(act)
  File "/usr/lib/python2.7/dist-packages/imagizer/interface.py", line 1058, in synchronize
    synchronize_dialog(self.idx_current, self.AllJpegs, self.selected)
  File "/usr/lib/python2.7/dist-packages/imagizer/dialogs.py", line 259, in synchronize_dialog
    logger.info(line)
  File "/usr/lib/python2.7/logging/__init__.py", line 1160, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1279, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1289, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1329, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 757, in handle
    self.emit(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 880, in emit
    stream.write(fs % msg)
KeyboardInterrupt

**Comment by kif** [comment]
fixed a while ago
